project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - assignments.qmd
    - index-pdf.qmd
    - slides/m1-ai-in-finance.qmd
    - slides/m2-intro-claude.qmd
    - slides/m3-mean-variance.qmd
    - slides/m4-claude.qmd
    - slides/m5-skills.qmd
    - slides/m6-makers-checkers.qmd
    - slides/m7-tips.qmd
    - slides/m8-scraping.qmd
    - slides/m9-agents.qmd
    - slides/m10-corporate.qmd
    - slides/m11-magnolia.qmd
    - slides/m12-rag.qmd
    - slides/m13-sentiment.qmd
    - slides/m14-agent-sdk.qmd
    - slides/m15-how-it-works.qmd
  resources:
    - CNAME
    - .nojekyll
    - slides/*.pdf
    - slides/m6-skills.html
    - slides/m5-dcf.html
    - files/*.zip
    - files/*.xlsx
    - files/*.csv
    - files/*.html
    - files/*.docx
    - files/*.md
    - files/*.py
    - files/*.db
    - slides/code/*.py
    - exercises/*.pdf
    - index-pdf.pdf
    - install/windows/windows-install.zip
    - install/windows/windows-install2.zip
    - install/mac/install.sh
  

website:
  title: ""
  search: false
  navbar:
    search: false
    title: MGMT 675
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides
      - href: assignments.qmd
        text: Assignments

format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true

comments:
  hypothesis: true
