## Slides and Notebooks<br>AI-Assisted Financial Analysis<br>Rice University<br>

Day 1: [html](day1.slides.html){target="_blank"} [pdf](pdfs/day1.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day1.ipynb){target="_blank"}<br>
Day 2: [html](day2.slides.html){target="_blank"} [pdf](pdfs/day2.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day2.ipynb){target="_blank"}<br>
Day 3: [html](day3.slides.html){target="_blank"} [pdf](pdfs/day3.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day3.ipynb){target="_blank"}<br>
Day 4: [html](day4.slides.html){target="_blank"} [pdf](pdfs/day4.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day4.ipynb){target="_blank"}<br>
Day 5: [html](day5.slides.html){target="_blank"} [pdf](pdfs/day5.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day5.ipynb){target="_blank"}<br>
Day 6: [html](day6.slides.html){target="_blank"} [pdf](pdfs/day6.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day6.ipynb){target="_blank"}<br>
Day 7: [html](day7.slides.html){target="_blank"} [pdf](pdfs/day7.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day7.ipynb){target="_blank"}<br>
Day 8: [html](day8.slides.html){target="_blank"} [pdf](pdfs/day8.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day8.ipynb){target="_blank"}<br>
Day 9: [html](day9.slides.html){target="_blank"} [pdf](pdfs/day9.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day9.ipynb){target="_blank"}<br>
Day 10: [html](day10.slides.html){target="_blank"} [pdf](pdfs/day10.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day10.ipynb){target="_blank"}<br>
Day 11: [html](day11.slides.html){target="_blank"} [pdf](pdfs/day11.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day11.ipynb){target="_blank"}<br>
Day 12: [html](day12.slides.html){target="_blank"} [pdf](pdfs/day12.slides.pdf){target="_blank"} [notebook](https://colab.research.google.com/github/kerryback/mgmt675/blob/main/notebooks/day12.ipynb){target="_blank"}<br>